# Generated by Django 2.0.12 on 2022-08-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=5)),
                ('devices', models.CharField(choices=[('ibmq_qasm_simulator', 'ibmq_qasm_simulator'), ('ibmq_bogota', 'ibmq_bogota'), ('ibmq_manila', 'ibmq_manila'), ('ibmq_santiago', 'ibmq_santiago'), ('ibmq_quito', 'ibmq_quito')], max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
