# Generated by Django 2.0.12 on 2022-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shors', '0002_auto_20220812_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='Number',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='factor',
            table='Shors_data',
        ),
    ]
