# Generated by Django 2.0.12 on 2022-08-12 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shors', '0004_factor_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('devices', models.CharField(choices=[('ibmq_qasm_simulator', 'ibmq_qasm_simulator'), ('ibmq_bogota', 'ibmq_bogota'), ('ibmq_manila', 'ibmq_manila'), ('ibmq_santiago', 'ibmq_santiago'), ('ibmq_quito', 'ibmq_quito')], default='ibmq_qasm_simulator', max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Shors_data',
            },
        ),
        migrations.DeleteModel(
            name='Factor',
        ),
    ]
