# Generated by Django 2.0.12 on 2022-08-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shors', '0005_auto_20220812_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='factormodel',
            table='Shors_algo_data',
        ),
    ]
