# Generated by Django 3.2 on 2022-08-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shors', '0007_auto_20220812_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factormodel',
            name='devices',
            field=models.CharField(choices=[('ibmq_qasm_simulator', 'ibmq_qasm_simulator'), ('aer_simulator', 'aer_simulator'), ('ibmq_manila', 'ibmq_manila'), ('ibmq_santiago', 'ibmq_santiago'), ('ibmq_quito', 'ibmq_quito')], default='ibmq_qasm_simulator', max_length=50),
        ),
        migrations.AlterField(
            model_name='factormodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
